- name: Remove floating IP from app1
  os_floating_ip:
    cloud: ospcloud
    state: absent
    server: app1
    network: ext_network

- name: Remove app1 server instance
  os_server:
    cloud: ospcloud
    name: app1
    state: absent
