- name: Remove floating IP to db
  os_floating_ip:
    cloud: ospcloud
    state: absent
    server: db
    network: ext_network
    
- name: Remove a db server instance
  os_server:
    cloud: ospcloud
    name: db
    state: absent
