
# Playbook to check OSP connection and network information

- hosts: workstation
  become: yes
  roles:
    - osp-check
 
- name: In momory inventory play
  hosts: localhost
  gather_facts: False
  tasks:  
  - name: Fetch Instance Info
    os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
    register: result

  - name: Add host
    add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }}"
      ansible_ssh_private_key_file: /home/cloud-user/.ssh/mykey.pem
      ansible_ssh_user: cloud-user
    with_items: "{{result.ansible_facts.openstack_servers}}"

  - name: Add host
    add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.deployment_name }}"
      ansible_ssh_private_key_file: /home/cloud-user/.ssh/mykey.pem
      ansible_ssh_user: cloud-user
    with_items: "{{result.ansible_facts.openstack_servers}}"
             
- hosts: all 
  gather_facts: true
  tasks:
  - debug:
      var=ansible_hostname

