- name: Gather facts about a previously created network by name
  os_networks_facts:
    name:  ext_network

- name: Show openstack networks
  debug:
    var: openstack_networks

- name: Gather facts about a previously created network by name
  os_networks_facts:
    name:  int_network

- name: Show openstack networks
  debug:
    var: openstack_networks

- name: Gather facts about ports
  os_port_facts:
    cloud: ospcloud

- name: Gather facts about all servers
  os_server_facts:
    cloud: ospcloud
- debug:
    var: openstack_servers
